# Generated by Django 4.2.18 on 2025-01-26 04:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hangout',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('deadline', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('idea collection', 'Idea Collection'), ('voting', 'Voting'), ('completed', 'Completed')], default='idea collection', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('vote_count', models.IntegerField(default=0)),
                ('hangout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.hangout')),
            ],
        ),
    ]
