# Generated by Django 4.2.18 on 2025-01-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hangout',
            old_name='deadline',
            new_name='submission_deadline',
        ),
        migrations.AddField(
            model_name='hangout',
            name='voting_deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
