# Generated by Django 4.2.18 on 2025-01-26 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_hangout_deadline_hangout_status_idea_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='session_id',
        ),
        migrations.RemoveField(
            model_name='vote',
            name='session_id',
        ),
    ]
