# Generated by Django 4.2.18 on 2025-01-26 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_remove_idea_session_id_remove_vote_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
